[project]
name = "hnefatafl"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.10"
dependencies = [
    "h5py>=3.14.0",
    "jupyterlab>=4.4.3",
    "lightning>=2.5.2",
    "torch>=2.7.1",
]
